version: "3.9"

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_app1
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=shortener
    networks:
      - shortener-net
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '20M'

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_app2
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=shortener
    networks:
      - shortener-net
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '20M'

  nginx:
    image: nginx:latest
    container_name: url_shortener_nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - shortener-net
    ports:
      - "9999:9999"
