version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: url_shortener_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"
    volumes:
      - shortnerdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shortener-net

    deploy:
        resources:
          limits:
              cpus: '0.3'
              memory: '360MB'

volumes:
  shortnerdata:

networks:
  shortener-net:
    
